# Generated by Django 4.2.15 on 2024-08-25 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departamentos',
            new_name='Setores',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='departamento',
            new_name='setor',
        ),
        migrations.RenameField(
            model_name='setores',
            old_name='nome_departamento',
            new_name='nome_setor',
        ),
        migrations.RenameField(
            model_name='treinamentos',
            old_name='departamento',
            new_name='setor',
        ),
        migrations.RemoveField(
            model_name='treinamentos',
            name='link',
        ),
        migrations.CreateModel(
            name='AcervoVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_video', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('url_video', models.URLField()),
                ('data_publicacao', models.DateField()),
                ('treinamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.treinamentos')),
            ],
        ),
    ]
