# Generated by Django 4.2.15 on 2024-08-25 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_departamentos_setores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acervovideos',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='acervovideos',
            name='data_publicacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
